Desitech/Desitech/urls.py
from django.contrib import admin
from django.urls import path , include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings 
from django.conf.urls.static import static 
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path ('accounts/' , include ('accounts.urls') ) ,
    path ('jobs/' , include ('jobs.urls') ) ,
    path ('' , views.index , name='home') ,
    path ('aboutus/' , views.about , name='about-us'),
    path ('contactus/' , views.Contact.as_view(), name='contact-us')
]


if settings.DEBUG:
        urlpatterns+= staticfiles_urlpatterns()
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Desitech/accounts/urls.py
from django.urls import path , include
from accounts.views import (
                                CompanyProfileView , JobSeekerProfileView , RegisterUserView ,
                                LogView , ResetPasswordView , MyProfile)
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from accounts.forms.SetNewPasswordForm import SetNewPasswordForm
from accounts.api.views.CountryView import AllCountries
from accounts.api.views.CityView import (AllCities , CitiesOfCountry)
from accounts.api.views.UserRegistrationView import UserRegistrationView
from accounts.api.views.UserLoginView import UserLoginView
from accounts.api.views.CompanyInformationView import CompanyInformationView
from accounts.api.views.JobSeekerInformationView import JobSeekerInformationView

app_name = "accounts"

urlpatterns = [

    path('rigester/', RegisterUserView.signup.as_view(), name='Register-User'),
    path('companyProfile/', CompanyProfileView.signup.as_view(), name='Company-profile'),
    path('jobSeekerProfile/', JobSeekerProfileView.signup.as_view(), name='JobSeeker-profile'),
    path('MyProfile/', MyProfile.MyProfile.as_view(), name='My-profile'),
    
    path('login/', LogView.log_user.as_view(), name='login'),
    path('logout/', LogView.logout_user, name='logout'),
   
   


    path("password_reset/", ResetPasswordView.ResetPassword.as_view(), name="password_reset"),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view
    (
        template_name="password/password_reset_confirm.html" , 
        success_url = reverse_lazy ('accounts:password_reset_complete') ,
        form_class = SetNewPasswordForm
    ),  name='password_reset_confirm'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(template_name='password/password_reset_complete.html') , name='password_reset_complete') ,
    


    path ('api/Country/All/' , AllCountries.as_view() , name = 'api-Country-All' ) ,
    path ('api/City/All/' , AllCities.as_view() , name = 'api-City-All' ) ,
    path ('api/CitiesOfCountry/<int:pk>/' , CitiesOfCountry.as_view() , name = 'api-Cities-Of-Country-All' ) ,

    path ('api/user/register/' , UserRegistrationView.as_view() , name = 'api-user-register' ) ,
    path ('api/user/login/' , UserLoginView.as_view() , name = 'api-user-login' ) ,
    path ('api/user/register/CompanyProfile/' , CompanyInformationView.as_view() , name = 'api-company-profile' ) ,
    path ('api/user/register/JobSeekerProfile/' , JobSeekerInformationView.as_view() , name = 'api-job-seeker-profile' ) ,
    ]

   

Desitech/jobs/urls.py
from django.urls import path 
from jobs.views import (JobCreateView , JobDeleteView , JobDetailView , 
                        JobUpdateView , AllJobsView  , MyJobs ,views)

from jobs.api.views.JobListView import AllJobsList
from jobs.api.views.JobByIdView import JobById
from jobs.api.views.JobsByCompany import JobsByCompany
from jobs.api.views.JobsByCity import JobsByCity
from jobs.api.views.AddJob import AddJob

app_name = 'jobs'

urlpatterns = [
    #site account urls
    path('listjobs/', AllJobsView.AllJobsView.as_view(), name='all-jobs-list'),
    path('myjobs/', MyJobs.MyJobs.as_view(),name='my-jobs'),
    path('create/', JobCreateView.JobCreateView.as_view(), name='job-create'),
    path('<int:pk>/update/',JobUpdateView.JobUpdateView.as_view(),name='job-update'),
    path('<int:pk>/delete/', JobDeleteView.JobDeleteView.as_view(),name='job-delete'),
    path('<int:pk>/', JobDetailView.JobDetailView.as_view(),name='job-detail'),

    #filter urls
    path('Filter/City', views.JobsByRegion ,name='job-filter-by-city'),
    path('Filter/Company', views.JobsByCompany ,name='job-filter-by-Company'),

    #ajax url
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities') , 

    #api urls
    path('api/job/allJobs/', AllJobsList.as_view(), name='api-job-alljobs') ,
    path('api/job/<int:pk>/', JobById.as_view(), name='api-job-by-id'),
    path('api/job/company/', JobsByCompany.as_view(), name='api-jobs-by-company'),
    path('api/job/city/<int:city_id>/', JobsByCity.as_view(), name='api-jobs-by-city'),
    path('api/job/add/', AddJob.as_view(), name='api-jobs-add'),
]

Desitech/templates/shared/_base.html
<!DOCTYPE html> 
{% load static %} 

<html lang="en">


<head>
   <meta charset="UTF-8">
    
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.3/css/intlTelInput.min.css" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.3/css/intlTelInput.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.0.0/animate.min.css"/>
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/logo.png' %}" sizes="50x50"/>
  <title>
   {% block title %} {% endblock %}
  </title>
  </head>
{% block head %} {% endblock head %}

<body>

<header class= 'header'>
            <div class="container">
                <nav class="navbar navbar-expand-lg navbar-light">
                    <a class="navbar-brand d-flex align-items-center justify-content-center"  href="{% url 'home' %}">
                        <h1 class="text-uppercase">dest 
                            <img src= {% static 'img/logo.png' %} alt= 'logo' class="img-fluid animate__animated animate__pulse animate__infinite infinite">
                            <span >tech</span></h1>
                    </a>
                    <button class="navbar-toggler  border-white" type="button" data-toggle="collapse" data-target="#navbarcollapse" aria-controls="navbarcollapse" aria-expanded="false" aria-label="Toggle navigation">
                       <i class="fa fa-bars icon-bar" aria-hidden="true"></i>
                    </button>
                  
                    <div class="collapse navbar-collapse" id="navbarcollapse">
                      <ul class="navbar-nav ml-auto text-capitalize">
                        <li class="nav-item active">
                          <a class="nav-link" href="{% url 'home' %}">home </a>
                        </li>
                        <li class="nav-item">
                           <a class="nav-link" href="{% url 'jobs:all-jobs-list' %}">jobs</a>
                        </li>
                         {% if user.is_company or user.is_superuser %}
                          <li class="nav-item">
                              <a class="nav-link" href="{% url 'jobs:my-jobs' %}">jobs dashBoard</a>
                          </li>
                        {% endif %}
                       

                        <li class="nav-item">
                             <a class="nav-link" href="{% url 'contact-us' %}">contact us</a>
                        </li>
                         <li class="nav-item">
                             <a class="nav-link" href="{% url 'about-us' %}">about us</a>
                        </li>
                        <li class="nav-item dropdown">
                          <a class="nav-link dropdown-toggle" href="#" id="account" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                             {% if not user.is_authenticated %}
                                account
                            {% elif user.is_company %}
                                {{user.company_profile.Name}}

                            {% elif user.is_job_seeker %}
                                {{user.job_seeker_profile.Name}}
                            {% endif %}
                            <i class="fa fa-user-circle-o" aria-hidden="true"></i>
                          </a>
                          <div class="dropdown-menu animate__animated animate__zoomIn" aria-labelledby="account">
                            
                            {% if not user.is_authenticated %}
                                <a class="dropdown-item" href="{% url 'accounts:Register-User' %}">sign up</a>
                                <a class="dropdown-item" href="{% url 'accounts:login' %}">login</a>
                            {% endif %}
                            {% if  user.is_authenticated %}
                                <a class="dropdown-item" href="{% url 'accounts:My-profile' %}">My Profile</a>
                                <a class="dropdown-item" href="{% url 'accounts:logout' %}">log out</a>
                            {% endif %}
                          </div>
                        </li>
                      </ul>
                    </div>
                  </nav>
            </div>
    </header>
    {% block content %} {% endblock %}
<footer>
        <div class="footer-top mt-5">
            <div class="container">
                <div class="row align-items-center justify-content-center text-center">
                    <div class=" col-md-3 col-sm-6 one mt-3">
                    <img src="{% static 'img/logo.png' %}" alt="" class="img-fluid" width="150px" height="150px">
                        <p class="lead">Design technologies company for technologies services
                        </p>
                    </div>
                    <div class=" col-md-3 col-sm-6 two mt-3 ">
                        <ul class= 'list-unstyled'>
                            <li class= ''><a href="#">platform</a></li>
                            <li class= '' ><a href="#">help center</a></li>
                            <li class= ''><a href="#">security</a></li>
                        </ul>
                    </div>
                    <div class="col-md-3 col-sm-6 two mt-3">
                        <ul class= 'list-unstyled'>
                            <li class= ''><a href="#">customers</a></li>
                            <li class= '' ><a href="#">use cases</a></li>
                            <li class= ''><a href="#">customers services</a></li>
                        </ul>
                    </div>
                    <div class="col-md-3 col-sm-6 two mt-3">
                        <ul class= 'list-unstyled'>
                            <li class= ''><a href="#">company</a></li>
                            <li class= '' ><a href="#">about us</a></li>
                            <li class= ''><a href="#">career we're hiring</a></li>
                        </ul>
                    </div>
                </div>
                <p class= 'footer-text text-capitalize mb-0 py-3 border-top'>
                    all right reserved by &copy; desitech 2020
                </p>
            </div>
        </div>
    </footer>
</body>

{% block scripts %}
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.3/js/intlTelInput.min.js"></script>
   
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<script type="text/javascript" src="{% static 'js/script.js' %}"></script>

{% endblock scripts %}

</html>