Desitech/Desitech/urls.py
from django.contrib import admin
from django.urls import path , include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings 
from django.conf.urls.static import static 
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path ('accounts/' , include ('accounts.urls') ) ,
    path ('jobs/' , include ('jobs.urls') ) ,
    path ('' , views.index , name='home') ,
    path ('aboutus/' , views.about , name='about-us'),
    path ('contactus/' , views.Contact.as_view(), name='contact-us')
]


if settings.DEBUG:
        urlpatterns+= staticfiles_urlpatterns()
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Desitech/jobs/urls.py
from django.urls import path 
from jobs.views import (JobCreateView , JobDeleteView , JobDetailView , 
                        JobUpdateView , AllJobsView  , MyJobs ,views)

from jobs.api.views.JobListView import AllJobsList
from jobs.api.views.JobByIdView import JobById
from jobs.api.views.JobsByCompany import JobsByCompany
from jobs.api.views.JobsByCity import JobsByCity
from jobs.api.views.AddJob import AddJob

app_name = 'jobs'

urlpatterns = [
    #site account urls
    path('listjobs/', AllJobsView.AllJobsView.as_view(), name='all-jobs-list'),
    path('myjobs/', MyJobs.MyJobs.as_view(),name='my-jobs'),
    path('create/', JobCreateView.JobCreateView.as_view(), name='job-create'),
    path('<int:pk>/update/',JobUpdateView.JobUpdateView.as_view(),name='job-update'),
    path('<int:pk>/delete/', JobDeleteView.JobDeleteView.as_view(),name='job-delete'),
    path('<int:pk>/', JobDetailView.JobDetailView.as_view(),name='job-detail'),

    #filter urls
    path('Filter/City', views.JobsByRegion ,name='job-filter-by-city'),
    path('Filter/Company', views.JobsByCompany ,name='job-filter-by-Company'),

    #ajax url
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities') , 

    #api urls
    path('api/job/allJobs/', AllJobsList.as_view(), name='api-job-alljobs') ,
    path('api/job/<int:pk>/', JobById.as_view(), name='api-job-by-id'),
    path('api/job/company/', JobsByCompany.as_view(), name='api-jobs-by-company'),
    path('api/job/city/<int:city_id>/', JobsByCity.as_view(), name='api-jobs-by-city'),
    path('api/job/add/', AddJob.as_view(), name='api-jobs-add'),
]

Desitech/jobs/models.py
from django.db import models
from accounts.models.User import User
from accounts.models.Country import Country
from accounts.models.City import City
from datetime import datetime

# Create your models here.



class Job (models.Model):

    publish_By =models.ForeignKey(User , on_delete=models.CASCADE)
    title = models.CharField(max_length=50) 
    abstract = models.TextField()
    skills = models.TextField()
    description = models.TextField()
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True)
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True)
    date = models.DateTimeField(auto_now_add=True)
    job_manger = models.Manager()

    def get_days_ago (self):
        return  datetime.now().day - self.date.day  
       

Desitech/jobs/api/views/AddJob.py
from rest_framework.generics import CreateAPIView 
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
from rest_framework_jwt.authentication import JSONWebTokenAuthentication
from rest_framework import status
from rest_framework.views import APIView

from accounts.models.User import User
from accounts.models.Country import Country
from accounts.models.City import City
from jobs.models import Job
from jobs.api.serializers.JobSerializer import JobSerializer


class AddJob(CreateAPIView):
  
    serializer_class = JobSerializer
    permission_classes = (IsAuthenticated,)
    authentication_class = JSONWebTokenAuthentication
   

    def post(self, request):
            
            if request.user.is_company :
                try:

                    Job.job_manger.create(
                        publish_By=request.user ,   
                        title = request.data['title'] ,
                        skills = request.data['skills'] ,
                        abstract = request.data['abstract'] ,
                        description = request.data['description'] ,
                        country = Country.objects.get (id = int(request.data['country'])) ,
                        city =  City.objects.get (id = int(request.data['city'])) ,
                        )

                    status_code = status.HTTP_200_OK
                    response = {'success' : 'True'}

                except Exception as err:
                    status_code = status.HTTP_406_NOT_ACCEPTABLE
                    response = {'error' : str(err) }

                return Response(response, status=status_code)
            else:
                status_code = status.HTTP_406_NOT_ACCEPTABLE
                response = {'error' :'register as company' ,'status code' : status_code}



   

Desitech/jobs/api/views/JobByIdView.py
from jobs.models import Job
from jobs.api.serializers.JobSerializer import JobSerializer

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from rest_framework.permissions import AllowAny , IsAuthenticated
from rest_framework_jwt.authentication import JSONWebTokenAuthentication



class JobById(APIView):
    permission_classes = (AllowAny,)
    # permission_classes = (IsAuthenticated,)
    # authentication_class = JSONWebTokenAuthentication
    
    def get(self, request, pk ,  format=None):

        try:

            job= Job.job_manger.get( pk=pk)
            jobDeatils = JobSerializer(job)
            status_code = status.HTTP_200_OK
            response = {'job' : jobDeatils.data ,}
            return Response(response , status_code)

        except Exception as err:
            status_code = status.HTTP_404_NOT_FOUND
            response = {'error' : str (err) ,}
            return Response (response , status_code)






# class JobDeatils(APIView):
  
#     def get(self, request , pk, format=None ):
#         jobs = job.job_manger.get( pk=pk)
#         jobq = JOBSerializer(jobs)
#         return Response(jobq.data)

Desitech/jobs/api/views/JobListView.py
from django.http import Http404
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from jobs.models import Job
from jobs.api.serializers.JobSerializer import JobSerializer
from rest_framework.permissions import AllowAny , IsAuthenticated
from rest_framework_jwt.authentication import JSONWebTokenAuthentication


class AllJobsList(APIView):
    permission_classes = (AllowAny,)
    # permission_classes = (IsAuthenticated,)
    # authentication_class = JSONWebTokenAuthentication
    

    def get(self, request, format=None):
        try:
            jobs = Job.job_manger.all().order_by('-date')
            allJobs = JobSerializer(jobs, many=True)
            status_code = status.HTTP_200_OK
            response = {'jobs' : allJobs.data , }
            return Response(response , status_code)

        except Exception as err :
            status_code = status.HTTP_404_NOT_FOUND
            response = {'error' : str (err) , }
            return Response (response , status_code)
          
          

Desitech/jobs/api/views/JobsByCity.py
from django.http import Http404
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from jobs.models import Job
from jobs.api.serializers.JobSerializer import JobSerializer
from rest_framework.permissions import AllowAny , IsAuthenticated
from rest_framework_jwt.authentication import JSONWebTokenAuthentication


class JobsByCity(APIView):
    permission_classes = (AllowAny,)
    # permission_classes = (IsAuthenticated,)
    # authentication_class = JSONWebTokenAuthentication
    

    def get(self, request , city_id , format=None):
        try: 
            jobs = Job.job_manger.filter(city = city_id).order_by('-date')
            jobsByCompany = JobSerializer(jobs, many=True)
            status_code = status.HTTP_200_OK
            response = {'jobs' : jobsByCompany.data , }
            return Response(response , status_code)

        except Exception as err :
            status_code = status.HTTP_404_NOT_FOUND
            response = {'error' : str (err) , }
            return Response (response , status_code)
          
          

Desitech/jobs/api/views/JobsByCompany.py
from django.http import Http404
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from jobs.models import Job
from jobs.api.serializers.JobSerializer import JobSerializer
from rest_framework.permissions import AllowAny , IsAuthenticated
from rest_framework_jwt.authentication import JSONWebTokenAuthentication


class JobsByCompany(APIView):
    # permission_classes = (AllowAny,)
    permission_classes = (IsAuthenticated,)
    authentication_class = JSONWebTokenAuthentication
    

    def get(self, request , format=None):
        try: 
            id = request.user.id
            jobs = Job.job_manger.filter(publish_By = id).order_by('-date')
            jobsByCompany = JobSerializer(jobs, many=True)
            status_code = status.HTTP_200_OK
            response = {'jobs' : jobsByCompany.data , }
            return Response(response , status_code)

        except Exception as err :
            status_code = status.HTTP_404_NOT_FOUND
            response = {'error' : str (err) , }
            return Response (response , status_code)
          
          

Desitech/jobs/views/AllJobsView.py
from django.views.generic import ListView
from jobs.models import Job
from accounts.models.CompanyProfile import Company_profile
from accounts.models.City import City


class AllJobsView(ListView):

    model = Job
    template_name = 'list_jobs.html'
    context_object_name = 'jobs'
    ordering = ['date']
    jobs = Job.job_manger.all()
    
    def get_context_data(self, **kwargs):
        context = super(AllJobsView, self).get_context_data(**kwargs)
        
        Cities = City.objects.all()
        Companies = Company_profile.objects.all()
        jobs = self.get_queryset()
        
        context['jobs'] = jobs
        context['jobsCount'] = len (jobs)

        context['Cities'] = Cities
        context['Companies'] = Companies

        return context

Desitech/jobs/views/JobCreateView.py
from django.views.generic.edit import CreateView
from django.shortcuts import HttpResponseRedirect
from django.utils.decorators import method_decorator
from django.urls import reverse
from jobs.models import Job ,City
from jobs.forms.JobCreateForm import JobForm
from Desitech.decorators import  is_company , is_company_or_admin , have_profile
from django.contrib.auth.decorators import login_required

login_decorator = login_required (login_url = 'accounts:login')


@method_decorator(login_decorator, name='dispatch')
@method_decorator(is_company_or_admin, name='dispatch')
@method_decorator(have_profile, name='dispatch')

class JobCreateView(CreateView):
    login_required = True
    model = Job
    form_class = JobForm
    template_name = 'add_job.html'
    #fields = ('publish_By' , 'title', 'skills' , 'text' , 'country' , 'city' )
   
    def get_success_url(self):
        return reverse('jobs:my-jobs')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.publish_By_id = self.request.user.id
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

  
   

Desitech/jobs/views/JobDeleteView.py
from jobs.models import Job
from django.views.generic.edit import DeleteView
from django.urls import reverse
from Desitech.decorators import  company_is_publish_job , is_company_or_admin , have_profile
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

login_decorator = login_required (login_url = 'accounts:login')

@method_decorator(login_decorator, name='dispatch')
@method_decorator(company_is_publish_job, name='dispatch')
@method_decorator(is_company_or_admin, name='dispatch')
@method_decorator(have_profile, name='dispatch')

class JobDeleteView(DeleteView):
    model = Job
    template_name = 'delete_job.html'

    def get_success_url(self):
        return reverse('jobs:my-jobs')

Desitech/jobs/views/JobDetailView.py
from django.views.generic.detail import DetailView
from jobs.models import Job
from django.contrib.auth.decorators import login_required




class JobDetailView(DetailView):

    model = Job
    template_name = 'job_detail.html'
    context_object_name = 'job'

Desitech/jobs/views/JobUpdateView.py
from django.views.generic.edit import UpdateView
from jobs.models import Job
from django.urls import reverse
from Desitech.decorators import  company_is_publish_job , is_company_or_admin , have_profile
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from jobs.forms.JobCreateForm import JobForm

login_decorator = login_required (login_url = 'accounts:login')

@method_decorator(login_decorator, name='dispatch')
@method_decorator(company_is_publish_job, name='dispatch')
@method_decorator(is_company_or_admin, name='dispatch')
@method_decorator(have_profile, name='dispatch')

class JobUpdateView(UpdateView):

    model = Job
    form_class = JobForm
    template_name = 'update_job.html'
    context_object_name = 'job'
  

    def get_success_url(self):
        return reverse('jobs:my-jobs')

 

Desitech/jobs/views/MyJobs.py
from jobs.models import Job
from django.views import View
from django.contrib.auth.decorators import login_required
from Desitech.decorators import is_company_or_admin , have_profile
from django.utils.decorators import method_decorator
from django.shortcuts import render
from django.core.paginator import Paginator

login_decorator = login_required (login_url = 'accounts:login')

@method_decorator(login_decorator, name='dispatch')
@method_decorator (is_company_or_admin , name='dispatch' )
@method_decorator (have_profile , name='dispatch' )

class MyJobs(View):

    def get (self , request):
        myjobs = Job.job_manger.filter (publish_By = request.user.id).order_by('-date')
        
        context =  {'myjobs' : myjobs , 'jobs': myjobs}
        return render ( request , 'jobs_dashboard.html' , context )
   

Desitech/jobs/views/views.py
from accounts.models.City import City
from django.shortcuts import render , HttpResponse ,redirect
from jobs.models import Job
from accounts.models.CompanyProfile import Company_profile

def load_cities(request):
    country_id = request.GET.get('country')
    cities = City.objects.filter(country_id=country_id).order_by('name')
    return render(request, 'cards/city_list_options.html', {'cities': cities})


def JobsByRegion(request):
    
    try:
        city = City.objects.get (name= request.POST.get('city'))
        jobsByCity = Job.job_manger.filter (city=city)
        msg = 'No jobs to view in {} city'.format(str (city)) 
        jobsCount = len (jobsByCity)
        context = { 'jobs' : jobsByCity , 'jobsCount' : jobsCount, 'empty' :msg ,}
        return render (request , 'JobSearh.html' , context)

    except Exception as exc:
        return redirect ('jobs:all-jobs-list')

 
    
def JobsByCompany(request):

    try:
        company = Company_profile.objects.get (Name= request.POST.get('company'))
        jobsBycompany = Job.job_manger.filter (publish_By=company.user)
        msg = 'No jobs published By  {} company'.format(str (company.Name)) 
        jobsCount = len (jobsBycompany)
        context = { 'jobs' : jobsBycompany , 'jobsCount' : jobsCount, 'empty' :msg , }
        return render (request , 'JobSearh.html' , context)

    except Exception as exc:
        return redirect ('jobs:all-jobs-list')

Desitech/jobs/templates/add_job.html
{% extends 'shared/_base.html' %}
{% load static %}
{% block title %} create job {% endblock %}

{% block content%}


          
<section class= 'createjobs my-5 mx-auto'>
        <div class="container">
            <div class="row rounded shadow-lg">
                <div class= "box1">
                    <h2 class= 'text-white text-capitalize text-right'>create a new job</h2>
                </div>
                <div class="col-sm-12 px-5">
                    <form method="post" id="Countries" data-cities-url="{% url 'jobs:ajax_load_cities' %}" novalidate>
                    {% csrf_token %}
                   
                      <div class="form-group">
                        <label for="id_title">{{form.title.label}}</label>
                         {{form.title}}
                      </div>
                     
                      <div class="form-row">
                       
                         <div class="form-group col-md-6">
                              
                                <label for="city">{{form.country.label}}</label>
                                {{form.country}}
                           
                            </div>
                       
                            <div class="form-group col-md-6">
                              
                                <label for="city">{{form.city.label}}</label>
                                {{form.city}}
                           
                            </div>
                           
                      </div>
                      <div class="form-group">
                                <label for="id_skills">{{form.abstract.label}}</label>
                                {{form.abstract}}
                        </div>

                        <div class="form-group">
                            <label for="id_skills">{{form.skills.label}}</label>
                             {{form.skills}}
                        </div>
                        <div class="form-group">
                            <label for="id_skills">{{form.description.label}}</label>
                             {{form.description}}
                        </div>
                  
                          <div class="form-group">
                           <button type="submit"  class='btn  my-3 text-uppercase'  id="myBtn">Create</button>
                          
                          </div>
                         
                    </form>
                    
                </div>
                <div class= "box">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320"><path fill="#fff" fill-opacity="1" d="M0,224L34.3,229.3C68.6,235,137,245,206,208C274.3,171,343,85,411,74.7C480,64,549,128,617,149.3C685.7,171,754,149,823,128C891.4,107,960,85,1029,112C1097.1,139,1166,213,1234,245.3C1302.9,277,1371,267,1406,261.3L1440,256L1440,0L1405.7,0C1371.4,0,1303,0,1234,0C1165.7,0,1097,0,1029,0C960,0,891,0,823,0C754.3,0,686,0,617,0C548.6,0,480,0,411,0C342.9,0,274,0,206,0C137.1,0,69,0,34,0L0,0Z"></path></svg>
                </div>
            </div>
        </div>
        
    </section>

{% endblock %}

Desitech/jobs/templates/delete_job.html
{% extends 'shared/_base.html' %}
{% load static %}
{% block title %} delete job {% endblock %}

{% block content%}
 <div class="container">
    <div  class="jumbotron ">
       <div class="row justify-content-md-center">
            <div class="card text-center" style="width: 35rem;">
                <div class="card text-center">
                    <div class="card-header">
                        <i class=" fa fa-trash fa-4x card-img-top" aria-hidden="true" id='delete-icon'></i>
                    </div>
                </div>

                <div class="card-body">
                    <h5 class="card-title"> Are you sure you want to delete</h5>
                    <p class="card-text">  <strong>'{{ object.title }}' job</p>
                    <p class="card-text">  <strong>with id : {{object.id}}</strong> ?</p>
                </div>
            
                <div class="card-footer">
                    <form method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary mr-5" id="filterBtn">Yes</button>
                        <a href="{% url 'jobs:my-jobs' %}" class="btn btn-primary ml-5 " id="filterBtn">No</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
 </div>
{% endblock %}

Desitech/jobs/templates/jobs_dashboard.html
{% extends 'shared/_base.html' %} 
{% load static %} 
{% block title %} jobs dashboard {% endblock %}
{% block content%}
<section class= 'mytablelist mx-auto my-5 p-2'>
    <div class="btn-add">
    <a href="{% url 'jobs:job-create' %}"><i class="fa fa-plus" aria-hidden="true"></i></a>
    </div>
    <div class="container">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col">
                        <div class="top_page  mb-5 py-2">
                            <h2>My jobs list</h2>
                        </div>
                        <div class="table-responsive my-3">
                            <table class="table table-hover my-3 text-center">
                                <thead>
                                    <tr>
                                        <th># job</th>
                                        <th>job title</th>
                                        <th>created time</th>
                                        <th>action</th>
                                    </tr>
                                </thead>
                                <tbody>
                  {% for job in jobs %}
                      <tr >
                          <td><strong>{{job.id}}</strong></td>
                          <td>{{job.title}}</td>
                          <td>{{job.date}}</td>
                          <td>
                                <a href= {% url 'jobs:job-detail' job.id %}><i class="fa fa-eye" aria-hidden="true"></i></a>
                                <a href= {% url 'jobs:job-update' job.id %} ><i class="fa fa-pencil" aria-hidden="true"></i></a>
                                <a href= {% url 'jobs:job-delete' job.id %}><i class="fa fa-trash-o" aria-hidden="true"></i></a>
                          </td>
                      </tr>
                  {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %} 

Desitech/jobs/templates/list_jobs.html
{% extends 'shared/_base.html' %}
{% load static %}
{% block title %} all jobs {% endblock %}
{% block content%}
 
  <section class= 'mytable mx-auto my-5 p-4 border'>
    <div class="container animate__animated animate__fadeInUp">
      <div class="row">
                    <div class="col-md-6 col-sm-12">
                         <form method='post' action = {% url 'jobs:job-filter-by-city'%}>
                         {% csrf_token %}
                            <div class="form-row">
                                <div class="form-group col-md-9">
                                    <div class="input-group my-3">
                                        <div class="input-group-prepend">
                                            <label class="input-group-text" for="filterbycity">filter by city</label>
                                        </div>
                                        <select class="form-control select" id="select"  name='city'>
                                              {% for city in Cities %}
                                                <option>{{city}}</option>
                                              {% endfor %}
                                          </select>
                                      </div>
                                </div>
                                <div class="form-group col-md-3 my-3">
                                    <input type="submit" class="btn btn-primary " id="filterBtn" value="Get">
                                  </div>
                            </div>
                        </form>
                    </div>
                    <div class="col-md-6 col-sm-12">
                         <form method='post' action = {% url 'jobs:job-filter-by-Company'%}>
                         {% csrf_token %}
                            <div class="form-row">
                                <div class="form-group col-md-9">
                                    <div class="input-group my-3">
                                        <div class="input-group-prepend">
                                            <label class="input-group-text" for="filterbycompany">filter by company</label>
                                        </div>
                                        <select class="form-control " id="select" name='company'>
                                           {% for company in Companies %}
                                                <option>{{company.Name}}</option>
                                            {% endfor %}
                                          </select>
                                      </div>
                                </div>
                                <div class="form-group col-md-3 my-3">
                                    <input type="submit" class="btn btn-primary " id="filterBtn" value="Get">
                                </div>
                            </div>
                        </form>
                    </div>
                  </div>
                <div class="row">
                    <div class="col-md-12 col-sm-12">
                        <div class="table-responsive my-3">
                            <table class="table table-hover my-3 " id='dataTable'>
                                <thead>
                                    <tr>
                                        <th scope="col">job title</th>
                                        <th scope="col">location</th>
                                        <th scope="col">company name</th>
                                        <th scope="col">date</th>
                                        <th scope="col">action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                  {% for job in jobs %}
                                      <tr >
                                          <td scope="row">{{job.title}}</td>
                                          <td>{{job.city}} - {{job.country}}</td>
                                          <td>{{job.publish_By.company_profile.Name}}</td>
                                          <td>{{job.date}}</td>
                                          <td><a href={% url 'jobs:job-detail' job.id %}><i class="fa fa-eye" aria-hidden="true"></i></a></td>
                                      </tr>
                                  {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
    </div>
</section>
{% endblock %}








































{% comment %} {% if page_obj.has_other_pages %}
  <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
      <li class="page-item">
         <a href="?page={{ page_obj.previous_page_number }}" class="page-link fa fa-angle-double-left"></a>

      </li>
      {% endif %} 
     
      {% if page_obj.has_next %}
      <li class="page-item">
         <a href="?page={{ page_obj.next_page_number }}" class="page-link fa fa-angle-double-right"></a>

      </li>
      {% endif %} 
  </ul>
 <p class="text-muted pagination justify-content-center">
       Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
</p>
 {% endif %}  {% endcomment %}

Desitech/jobs/templates/update_job.html
{% extends 'shared/_base.html' %}
{% load static %}
{% block title %} update job {% endblock %}

{% block content%}

<section class= 'createjobs my-5 mx-auto'>
        <div class="container">
            <div class="row rounded shadow-lg">
                <div class= "box1">
                    <h2 class= 'text-white text-capitalize text-right'>Update job</h2>
                </div>
                <div class="col-sm-12 px-5">
                    <form method="post" id="Countries" data-cities-url="{% url 'jobs:ajax_load_cities' %}" novalidate>
                    {% csrf_token %}
                   
                      <div class="form-group">
                        <label for="id_title">{{form.title.label}}</label>
                         {{form.title}}
                      </div>
                     
                      <div class="form-row">
                       
                         <div class="form-group col-md-6">
                              
                                <label for="city">{{form.country.label}}</label>
                                {{form.country}}
                           
                            </div>
                       
                            <div class="form-group col-md-6">
                              
                                <label for="city">{{form.city.label}}</label>
                                {{form.city}}
                           
                            </div>
                           
                      </div>
                      <div class="form-group">
                                <label for="id_skills">{{form.abstract.label}}</label>
                                {{form.abstract}}
                        </div>

                        <div class="form-group">
                            <label for="id_skills">{{form.skills.label}}</label>
                             {{form.skills}}
                        </div>
                        <div class="form-group">
                            <label for="id_skills">{{form.description.label}}</label>
                             {{form.description}}
                        </div>
                  
                          <div class="form-group">
                           <button type="submit"  class='btn  my-3 text-uppercase'  id="myBtn">UpDate</button>
                          
                          </div>
                         
                    </form>
                    
                </div>
                <div class= "box">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320"><path fill="#fff" fill-opacity="1" d="M0,224L34.3,229.3C68.6,235,137,245,206,208C274.3,171,343,85,411,74.7C480,64,549,128,617,149.3C685.7,171,754,149,823,128C891.4,107,960,85,1029,112C1097.1,139,1166,213,1234,245.3C1302.9,277,1371,267,1406,261.3L1440,256L1440,0L1405.7,0C1371.4,0,1303,0,1234,0C1165.7,0,1097,0,1029,0C960,0,891,0,823,0C754.3,0,686,0,617,0C548.6,0,480,0,411,0C342.9,0,274,0,206,0C137.1,0,69,0,34,0L0,0Z"></path></svg>
                </div>
            </div>
        </div>
        
    </section>
      
{% endblock %}