Desitech/Desitech/urls.py
from django.contrib import admin
from django.urls import path , include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings 
from django.conf.urls.static import static 
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path ('accounts/' , include ('accounts.urls') ) ,
    path ('jobs/' , include ('jobs.urls') ) ,
    path ('' , views.index , name='home') ,
    path ('aboutus/' , views.about , name='about-us'),
    path ('contactus/' , views.Contact.as_view(), name='contact-us')
]


if settings.DEBUG:
        urlpatterns+= staticfiles_urlpatterns()
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Desitech/accounts/urls.py
from django.urls import path , include
from accounts.views import (
                                CompanyProfileView , JobSeekerProfileView , RegisterUserView ,
                                LogView , ResetPasswordView , MyProfile)
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from accounts.forms.SetNewPasswordForm import SetNewPasswordForm
from accounts.api.views.CountryView import AllCountries
from accounts.api.views.CityView import (AllCities , CitiesOfCountry)
from accounts.api.views.UserRegistrationView import UserRegistrationView
from accounts.api.views.UserLoginView import UserLoginView
from accounts.api.views.CompanyInformationView import CompanyInformationView
from accounts.api.views.JobSeekerInformationView import JobSeekerInformationView

app_name = "accounts"

urlpatterns = [

    path('rigester/', RegisterUserView.signup.as_view(), name='Register-User'),
    path('companyProfile/', CompanyProfileView.signup.as_view(), name='Company-profile'),
    path('jobSeekerProfile/', JobSeekerProfileView.signup.as_view(), name='JobSeeker-profile'),
    path('MyProfile/', MyProfile.MyProfile.as_view(), name='My-profile'),
    
    path('login/', LogView.log_user.as_view(), name='login'),
    path('logout/', LogView.logout_user, name='logout'),
   
   


    path("password_reset/", ResetPasswordView.ResetPassword.as_view(), name="password_reset"),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view
    (
        template_name="password/password_reset_confirm.html" , 
        success_url = reverse_lazy ('accounts:password_reset_complete') ,
        form_class = SetNewPasswordForm
    ),  name='password_reset_confirm'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(template_name='password/password_reset_complete.html') , name='password_reset_complete') ,
    


    path ('api/Country/All/' , AllCountries.as_view() , name = 'api-Country-All' ) ,
    path ('api/City/All/' , AllCities.as_view() , name = 'api-City-All' ) ,
    path ('api/CitiesOfCountry/<int:pk>/' , CitiesOfCountry.as_view() , name = 'api-Cities-Of-Country-All' ) ,

    path ('api/user/register/' , UserRegistrationView.as_view() , name = 'api-user-register' ) ,
    path ('api/user/login/' , UserLoginView.as_view() , name = 'api-user-login' ) ,
    path ('api/user/register/CompanyProfile/' , CompanyInformationView.as_view() , name = 'api-company-profile' ) ,
    path ('api/user/register/JobSeekerProfile/' , JobSeekerInformationView.as_view() , name = 'api-job-seeker-profile' ) ,
    ]

   

Desitech/jobs/urls.py
from django.urls import path 
from jobs.views import (JobCreateView , JobDeleteView , JobDetailView , 
                        JobUpdateView , AllJobsView  , MyJobs ,views)

from jobs.api.views.JobListView import AllJobsList
from jobs.api.views.JobByIdView import JobById
from jobs.api.views.JobsByCompany import JobsByCompany
from jobs.api.views.JobsByCity import JobsByCity
from jobs.api.views.AddJob import AddJob

app_name = 'jobs'

urlpatterns = [
    #site account urls
    path('listjobs/', AllJobsView.AllJobsView.as_view(), name='all-jobs-list'),
    path('myjobs/', MyJobs.MyJobs.as_view(),name='my-jobs'),
    path('create/', JobCreateView.JobCreateView.as_view(), name='job-create'),
    path('<int:pk>/update/',JobUpdateView.JobUpdateView.as_view(),name='job-update'),
    path('<int:pk>/delete/', JobDeleteView.JobDeleteView.as_view(),name='job-delete'),
    path('<int:pk>/', JobDetailView.JobDetailView.as_view(),name='job-detail'),

    #filter urls
    path('Filter/City', views.JobsByRegion ,name='job-filter-by-city'),
    path('Filter/Company', views.JobsByCompany ,name='job-filter-by-Company'),

    #ajax url
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities') , 

    #api urls
    path('api/job/allJobs/', AllJobsList.as_view(), name='api-job-alljobs') ,
    path('api/job/<int:pk>/', JobById.as_view(), name='api-job-by-id'),
    path('api/job/company/', JobsByCompany.as_view(), name='api-jobs-by-company'),
    path('api/job/city/<int:city_id>/', JobsByCity.as_view(), name='api-jobs-by-city'),
    path('api/job/add/', AddJob.as_view(), name='api-jobs-add'),
]

Desitech/accounts/models/City.py
from django.db import models
from accounts.models.Country import Country

class City(models.Model):
    
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)

    class Meta:
        verbose_name_plural = "Cities"

    def __str__(self):
        return self.name
        
    @property
    def getName (self):
        return self.name

Desitech/accounts/models/CompanyProfile.py
from django.db import models
from accounts.models.User import User
from accounts.models.Country import Country
from accounts.models.City import City
from django.conf import settings
from django.core.validators import RegexValidator

class Company_profile (models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE , primary_key=True)
    Name =models.CharField(max_length=50 )
    country = models.ForeignKey(Country, on_delete=models.SET_NULL , null=True)
    city = models.ForeignKey(City, on_delete=models.SET_NULL , null=True)
    street = models.CharField(max_length=128 , null=True)
    building_number = models.IntegerField(null=True)
    zip_code =  models.CharField("ZIP / Postal code", max_length=12, null=True)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', 
                    message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    
    phone_number = models.CharField( validators=[phone_regex] , max_length=17 , null=True) 
    mobile_number = models.CharField( validators=[phone_regex] ,max_length=17 , null=True) 

   

Desitech/accounts/models/JobSeekerProfile.py
from django.db import models
from accounts.models.User import User
from django.core.validators import FileExtensionValidator
from accounts.models.Country import Country
from accounts.models.City import City
from django.conf import settings
from django.core.validators import RegexValidator
from datetime import datetime



class job_seeker_profile (models.Model):
    
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),)

    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE , primary_key=True)
    Name = models.CharField(max_length=30 , null=False)
    surname = models.CharField(max_length=30 , null=True)
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True)
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True)
    nationality = models.CharField(max_length=50 , null=True)
    birth_date = models.DateField(blank=True, null=True)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES , null=True)
    zip_code =  models.CharField("ZIP / Postal code", max_length=12,null=True)
    street =models.CharField(max_length=128 , null=True)
    house_number = models.IntegerField(null=True)
    personal_photo =models.ImageField(upload_to='images/' , null=True)
    CV = models.FileField(upload_to='CV/',validators=[FileExtensionValidator(allowed_extensions=['pdf'])] , null=True) 
    cover_letter = models.TextField(null=True)
   
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', 
                    message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    
    phone_number = models.CharField( validators=[phone_regex] , max_length=17 , null=True) 
    mobile_number = models.CharField( validators=[phone_regex] ,max_length=17 , null=True)  


    @property
    def age(self):
        return int((datetime.now().date() - self.birth_date).days / 365.25)
    
    @property
    def sex(self):
        if self.gender == 'M':
            return 'Male'
        if self.gender == 'F':
             return 'FeMale'

Desitech/accounts/forms/ContactForm.py
from django import forms
from accounts.models.ContactUs import ContactUs


class contactUs (forms.ModelForm):

    class Meta:
        model = ContactUs
        fields = ("Subject" , 'Message' ,)
        labels= { 
                'Subject': 'Subject', 
                'Message': 'Message',
                }

        widgets = {
            'Subject': forms.TextInput(attrs={'class': 'form-control', 'placeholder': "Subject"}),
            'Message': forms.Textarea(attrs={'class': 'form-control', 'placeholder': "Write your Message here" , 'style':'resize: none;'}), 
            }

Desitech/accounts/api/views/CityView.py
from accounts.models.City import City
from accounts.api.serializers.CitySerializer import CitySerializer

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from rest_framework.permissions import AllowAny 



class CitiesOfCountry(APIView):
    permission_classes = (AllowAny,)
   
    def get(self, request, pk ,  format=None):

        try:

            cities= City.objects.filter(country=pk)
          
            citiesDeatils = CitySerializer(cities , many=True)
            status_code = status.HTTP_200_OK
            response = { 'cities' : citiesDeatils.data , }
            return Response(response , status_code)

        except Exception as err:
            status_code = status.HTTP_404_NOT_FOUND
            response = {'error' : str (err) ,}
            return Response (response , status_code)


class AllCities(APIView):
    permission_classes = (AllowAny,)
   
    def get(self, request ,  format=None):

        try:

            cities= City.objects.all()
            
            citiesDeatils = CitySerializer(cities, many=True)
           
            status_code = status.HTTP_200_OK
            response = {'cities' : citiesDeatils.data ,}
            return Response(response , status_code)

        except Exception as err:
            status_code = status.HTTP_404_NOT_FOUND
            response = {'error' : str (err) ,}
            return Response (response , status_code)










 

Desitech/accounts/api/views/CompanyInformationView.py
from rest_framework.generics import CreateAPIView 
from accounts.models.CompanyProfile import Company_profile
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated , AllowAny
from rest_framework_jwt.authentication import JSONWebTokenAuthentication
from rest_framework import status
from rest_framework.views import APIView
from accounts.api.serializers.ProfileSerializer import CompanySerializer
from accounts.models.Country import Country
from accounts.models.City import City

class CompanyInformationView(CreateAPIView):
    # permission_classes = (AllowAny,)
    permission_classes = (IsAuthenticated,)
    authentication_class = JSONWebTokenAuthentication
    
    def post(self, request):
    
        if request.user.is_company :
           
            try:
                Company_profile.objects.create(
                    user=request.user ,   
                    Name = request.data['Name'] ,
                    zip_code = request.data['zip_code'] ,
                    street = request.data['street'] ,
                    building_number = request.data['building_number'] ,
                    phone_number = request.data['phone_number'] ,
                    mobile_number = request.data['mobile_number'] ,
                    country = Country.objects.get (id = int(request.data['country'])) ,
                    city =  City.objects.get (id = int(request.data['city'])) ,

                    )
                status_code = status.HTTP_200_OK
                response = {'success' : 'True',}
            except Exception as err:
               
                status_code = status.HTTP_406_NOT_ACCEPTABLE
                response = {'error' : str(err) ,}
        

            return Response(response, status=status_code)


   

Desitech/accounts/api/views/CountryView.py
from accounts.models.Country import Country
from accounts.api.serializers.CountrySerializer import CountrySerializer

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from rest_framework.permissions import AllowAny 






class AllCountries(APIView):
    permission_classes = (AllowAny,)
   
    def get(self, request,  format=None):

        try:

            countries= Country.objects.all()
            
            countriesDeatils = CountrySerializer(countries, many=True)
           
            status_code = status.HTTP_200_OK
            response = {'countries' : countriesDeatils.data ,}
            return Response(response , status_code)

        except Exception as err:
            status_code = status.HTTP_404_NOT_FOUND
            response = {'error' : str (err) ,}
            return Response (response , status_code)

Desitech/accounts/api/views/JobSeekerInformationView.py
from rest_framework.generics import CreateAPIView 
from accounts.models.JobSeekerProfile import job_seeker_profile
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
from rest_framework_jwt.authentication import JSONWebTokenAuthentication
from rest_framework import status
from rest_framework.views import APIView
from rest_framework.parsers import MultiPartParser

from accounts.api.serializers.ProfileSerializer import JobSeekerProfileSerializer
from accounts.models.Country import Country
from accounts.models.City import City
import json

class JobSeekerInformationView(CreateAPIView):
    permission_classes = (IsAuthenticated,)
    authentication_class = JSONWebTokenAuthentication
    parser_classes = (MultiPartParser,)

    def post(self, request):
       
        
        if request.user.is_job_seeker :
            try:
            
                jsonsString = request.data['data']

                jsonString = jsonsString.replace ("\'" , "\"")
               
                data = json.loads(jsonString)
                
                job_seeker_profile.objects.create(
                    user=request.user , 
                    Name = data['Name'] ,
                    surname = data['surname'] ,
                    country = Country.objects.get (id = int(data['country'])) ,
                    city =  City.objects.get (id = int(data['city'])) ,
                    nationality =  data['nationality'] ,
                    birth_date =  data['birth_date'] ,
                    gender = data['gender'] ,
                    zip_code =  data['zip_code'] ,
                    street =  data['street'] ,
                    house_number =  data['house_number'] ,
                    personal_photo =  request.FILES['personal_photo'] ,
                    CV =  request.FILES['CV'] ,
                    cover_letter =  data['cover_letter'] ,
                    phone_number =  data['phone_number'] ,
                    mobile_number =  data['mobile_number'] ,    
                    )

                status_code = status.HTTP_200_OK
                response = {'success' : 'True'}
            except Exception as err:
             
                status_code = status.HTTP_406_NOT_ACCEPTABLE
                response = {'error' : str(err) }
        

            return Response(response, status=status_code)
        else:
            response = {'error' : 'this url is only for job seeker user , check auth or type of user.' }

   

Desitech/accounts/api/views/UserLoginView.py
from accounts.api.serializers.UserLoginSerializer import UserLoginSerializer 
from rest_framework import status
from rest_framework.response import Response
from rest_framework.permissions import AllowAny
from rest_framework.permissions import IsAuthenticated
from rest_framework_jwt.authentication import JSONWebTokenAuthentication
from rest_framework.generics import  RetrieveAPIView


class UserLoginView(RetrieveAPIView):

    permission_classes = (AllowAny,)
    serializer_class = UserLoginSerializer
   
    def post(self, request):
      
        try:
           
            serializer = self.serializer_class(data=request.data)
            
            serializer.is_valid(raise_exception=True)
         
            response = {
               
                'user_id' : serializer.data['user_id'] ,
                'user_type' :  serializer.data['user_type'] ,
                'token' : serializer.data['token'],
                'completed' :  serializer.data['completed'] ,
                }
          
            status_code = status.HTTP_200_OK
        except Exception as err:
            status_code = status.HTTP_406_NOT_ACCEPTABLE
            response = {'error' : str (err)}
        return Response(response, status=status_code)

Desitech/accounts/templates/company_signup.html
{% extends 'shared/_base.html' %}
{% block title %} {{page_title}} {% endblock %}
{% load static %}



{% block content%}


  <section class= 'theBody my-5 mx-auto'>
     
        <div class="title d-flex align-items-center justify-content-center text-center">
          <div class="info">
            <h2 class= 'companytitle'>Company Profile Information</h2>
          </div>
        </div>
        
            <div class="container">
                <div class="row rounded shadow-lg">
                    <div class="col-sm-12 px-5">
                    <p class= 'lead text-center pb-3 text '>complete your company info to rigester <br>thanks for fill in form.</p>
                        <form method="post" id="Countries" data-cities-url="{% url 'jobs:ajax_load_cities' %}" novalidate>
                        {% csrf_token %}
                          <div class="form-group">
                            <label for="id_Name">{{company_profile_form.Name.label}}</label>
                            {{company_profile_form.Name}}
                          <small class = 'text-muted'> {{company_profile_form.Name.errors}} </small>
                          </div>
                         
                          <div class="form-group">
                              
                            <label for="id_country">{{company_profile_form.country.label}}</label>
                            {{company_profile_form.country}}
                             <small class = 'text-muted'>  {{company_profile_form.country.errors}} </small>
                          </div>
                        
                          <div class="form-group">
                            <label for="id_city">{{company_profile_form.city.label}}</label>
                              {{company_profile_form.city}}
                              <small class = 'text-muted'>  {{company_profile_form.city.errors}} </small>
                          </div>
                         
                          <div class="form-group">
                            <label for="id_zip_code">{{company_profile_form.zip_code.label}}</label>
                            {{company_profile_form.zip_code}}
                              <small class = 'text-muted'>  {{company_profile_form.zip_code.errors}} </small>
                          </div>
                        
                          <div class="form-group">
                            <label for="id_street">{{company_profile_form.street.label}}</label>
                            {{company_profile_form.street}}
                             <small class = 'text-muted'>  {{company_profile_form.street.errors}} </small>
                          </div>
                         
                          <div class="form-group">
                            <label for="id_building_number">{{company_profile_form.building_number.label}}</label>
                            {{company_profile_form.building_number}}
                             <small class = 'text-muted'>  {{company_profile_form.building_number.errors}} </small>
                          </div>
                         
                          <div class="form-group">
                              <label for="id_phone_number">{{company_profile_form.phone_number.label}}</label>
                               {{company_profile_form.phone_number}}
                                <small class = 'text-muted'>  {{company_profile_form.phone_number.errors}} </small>
                          </div>
                        
                          <div class="form-group">
                            <label for="id_mobile_number">{{company_profile_form.mobile_number.label}}</label>
                            {{company_profile_form.mobile_number}}
                             <small class = 'text-muted'>  {{company_profile_form.mobile_number.errors}} </small>
                        </div>
                      
                             <div class="form-group">
                                  <button type="submit" class='btn  my-3' id='myBtn'>continue</button>
                                </div>
                             
                        </form>
                      
                    </div>
                </div>
            </div>
       </section>


{% endblock %}

Desitech/accounts/templates/jobseeker_signup.html
{% extends 'shared/_base.html' %}
{% block title %} {{page_title}} {% endblock %}
{% load static %}


{% block content%}
<section class= 'theBody my-5 mx-auto'>
            <div class="container">
                <div class="row rounded shadow-lg">
                  
                    <div class="accountBox  align-items-center justify-content-center text-white text-center">
                      <h2 class= 'my-3 py-3 text-capitalize'>job seeker profile Information</h2>
                      <div class="photo">
                        <img src="{% static 'img/Mask@3x.png' %}" alt="" class= 'img-fluid' style = 'width:200px ; height:200px'>
                      </div>
                      <div class="accountdata py-3">
                        <h3 class="text-capitalize text-white">{{user.email}}</h3>
                       
                      </div>
                    </div>
                   
                    <div class="col-md-12 px-5 mt-4">
                        <form  method="post"  enctype="multipart/form-data" id="Countries" data-cities-url="{% url 'jobs:ajax_load_cities' %}"  novalidate>
                          {% csrf_token %}
                          
                          <div class="form-group">
                            <label for="id_Name">{{JobSeeker_profile_form.Name.label}}</label>
                            {{JobSeeker_profile_form.Name}}
                            <small class = 'text-muted'>  {{JobSeeker_profile_form.Name.errors}} </small>
                          </div>
                         
                          <div class="form-group">
                            <label for="id_surname">{{JobSeeker_profile_form.surname.label}}</label>
                            {{JobSeeker_profile_form.surname}}
                            <small class = 'text-muted'>  {{JobSeeker_profile_form.surname.errors}} </small>
                          </div>
                        
                              <div class="form-group">
                                <legend class="col-form-label py-3"> {{JobSeeker_profile_form.gender.label}} </legend>
                                 {{JobSeeker_profile_form.gender}}
                                  <small class = 'text-muted'>  {{JobSeeker_profile_form.gender.errors}} </small>
                              </div>
                            
                            
                              <div class="form-group">
                                <label for="id_country_of_residence"> {{JobSeeker_profile_form.nationality.label}}</label>
                                {{JobSeeker_profile_form.nationality}}
                                 <small class = 'text-muted'>  {{JobSeeker_profile_form.nationality.errors}} </small>
                              </div>
                             
                              <div class="form-group">
                                <label for="dateofbirth"> {{JobSeeker_profile_form.birth_date.label}}</label>
                                 {{JobSeeker_profile_form.birth_date}}
                                  <small class = 'text-muted'>  {{JobSeeker_profile_form.birth_date.errors}} </small>
                              </div>

                               <div class="form-group">
                                <label for="id_mobile_number">{{JobSeeker_profile_form.house_number.label}}</label>
                                {{JobSeeker_profile_form.house_number}}
                                <small class = 'text-muted'>  {{JobSeeker_profile_form.house_number.errors}} </small>
                              </div>

                               <div class="form-group">
                                 <label for="id_phone_number">{{JobSeeker_profile_form.phone_number.label}}</label>
                                 {{JobSeeker_profile_form.phone_number}}
                                  <small class = 'text-muted'>  {{JobSeeker_profile_form.phone_number.errors}} </small>
                               </div>

                            
                           
                          <div class="form-group">
                              <label for="id_mobile_number">{{JobSeeker_profile_form.mobile_number.label}}</label>
                              {{JobSeeker_profile_form.mobile_number}}
                              <small class = 'text-muted'>  {{JobSeeker_profile_form.mobile_number.errors}} </small>
                          </div>

                     
                         <div class="form-group">
                              <label for="id_CV">{{JobSeeker_profile_form.CV.label}}</label>
                              
                              {{JobSeeker_profile_form.CV}}
                              <small class = 'text-muted'>  {{JobSeeker_profile_form.CV.errors}} </small>
                          </div>
                       
                          <div class="form-group">
                              <label for="id_personal_photo">{{JobSeeker_profile_form.personal_photo.label}}</label>
                              {{JobSeeker_profile_form.personal_photo}}
                              <small class = 'text-muted'>  {{JobSeeker_profile_form.personal_photo.errors}} </small>
                          </div>
                      
                         <div class="form-group">
                              
                            <label for="id_country"> {{JobSeeker_profile_form.country.label}}</label>
                            {{JobSeeker_profile_form.country}}
                            <small class = 'text-muted'>  {{JobSeeker_profile_form.country.errors}} </small>
                           
                          </div>
                         
                          <div class="form-group">
                            <label for="id_city"> {{JobSeeker_profile_form.city.label}}</label>
                            {{JobSeeker_profile_form.city}}
                             <small class = 'text-muted'>  {{JobSeeker_profile_form.city.errors}} </small>
                          </div>
                         
                          <div class="form-group">
                            <label for="id_zip_code">{{JobSeeker_profile_form.zip_code.label}}</label>
                            {{JobSeeker_profile_form.zip_code}}
                             <small class = 'text-muted'>  {{JobSeeker_profile_form.zip_code.errors}} </small>
                          </div>
                         
                          <div class="form-group">
                            <label for="id_street"> {{JobSeeker_profile_form.street.label}}</label>
                            {{JobSeeker_profile_form.street}}
                              <small class = 'text-muted'>  {{JobSeeker_profile_form.street.errors}} </small>
                          </div>
                         
                           <div class="form-group">
                            <label for="id_building_number"> {{JobSeeker_profile_form.building_number.label}}</label>
                            {{JobSeeker_profile_form.building_number}}
                            <small class = 'text-muted'>  {{JobSeeker_profile_form.building_number.errors}} </small>
                          </div>

                          <div class="form-group">
                            <label for="id_cover_letter"> {{JobSeeker_profile_form.cover_letter.label}}</label>
                            {{JobSeeker_profile_form.cover_letter}}
                            <small class = 'text-muted'>  {{JobSeeker_profile_form.cover_letter.errors}} </small>
                          </div>
                         
                                <div class="form-group">
                                  <button type="submit" class='btn  my-3' id='myBtn'>continue</button>
                                </div>
                        </form>
                     
                    </div>
                </div>
            </div>
       </section>
{% endblock %}